name: Build Project

on:
  push:
    branches:
      - branchMake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: make
